{% set version = "2.4-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-treemap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/treemap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/treemap/treemap_{{ version }}.tar.gz
  sha256: c55a8b271f16405a283978cd4e0bef7192840b397aa7bb6fbbf9233b875677c0

build:
  noarch: generic
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-colorspace
    - r-data.table >=1.8.8
    - r-ggplot2
    - r-gridbase
    - r-igraph
    - r-shiny >=0.12.0
  run:
    - r-base
    - r-rcolorbrewer
    - r-colorspace
    - r-data.table >=1.8.8
    - r-ggplot2
    - r-gridbase
    - r-igraph
    - r-shiny >=0.12.0

test:
  commands:
    - $R -e "library('treemap')"           # [not win]
    - "\"%R%\" -e \"library('treemap')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=treemap
  license: GPL-3.0-only
  summary: A treemap is a space-filling visualization of hierarchical structures. This package offers great flexibility to draw treemaps.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
